#!/usr/bin/env bash
# Tokoflow Positioning Loop — generated by ~/.claude/skills/infinite-loop
# Per-cycle work: see docs/positioning/loop/LOOP_INSTRUCTIONS.md
# Edits to the EDIT block below are expected. Do not modify the loop logic.

set -u  # fail on undefined vars, but NOT set -e (failed cycles must not kill loop)

# ─── EDIT THESE ──────────────────────────────────────────────────────────────
PROJECT_DIR="${PROJECT_DIR:-/Users/muhamadaldiansyah/base/tokoflow}"
PROMPT="${PROMPT:-You are running ONE cycle of the Tokoflow positioning loop. Read docs/positioning/loop/LOOP_INSTRUCTIONS.md for the full mandate. Determine current cycle from \$LOOP_CYCLE env var. Read disk state (current-best.md, scoreboard.md, CHANGELOG.md last 3 lines, latest cycle artifact) before any work. Execute exactly ONE cycle per the mode-selection table. Use ultrathink throughout — radical ideas, not refinement. Exit cleanly when done. Do NOT run multiple cycles in one session.}"
ALLOWED_TOOLS="${ALLOWED_TOOLS:-Bash,Read,Write,Edit,Glob,Grep,Agent,WebSearch,WebFetch}"
MAX_CYCLES="${MAX_CYCLES:-20}"
CYCLE_TIMEOUT="${CYCLE_TIMEOUT:-2400}"   # 40 min — research cycles can be long
PERMISSION_MODE="${PERMISSION_MODE:-acceptEdits}"
# ─────────────────────────────────────────────────────────────────────────────

LOG_DIR="$PROJECT_DIR/runs"
LOG="$LOG_DIR/loop.log"
COUNTER_FILE="$LOG_DIR/.loop-counter"
CONVERGED_SENTINEL="$PROJECT_DIR/docs/positioning/loop/CONVERGED.md"

mkdir -p "$LOG_DIR"
[ -f "$COUNTER_FILE" ] || echo 0 > "$COUNTER_FILE"

log() {
  echo "[$(date -Iseconds)] $*" | tee -a "$LOG"
}

# Portable timeout — macOS doesn't ship GNU `timeout(1)`. This mimics it:
# returns 124 when the command was killed for exceeding timeout_secs.
run_with_timeout() {
  local timeout_secs="$1"; shift

  "$@" &
  local cmd_pid=$!

  (
    sleep "$timeout_secs"
    if kill -0 "$cmd_pid" 2>/dev/null; then
      kill -TERM "$cmd_pid" 2>/dev/null
      sleep 5
      kill -KILL "$cmd_pid" 2>/dev/null
    fi
  ) >/dev/null 2>&1 &
  local watcher_pid=$!

  wait "$cmd_pid" 2>/dev/null
  local rc=$?

  if kill -0 "$watcher_pid" 2>/dev/null; then
    kill "$watcher_pid" 2>/dev/null
    wait "$watcher_pid" 2>/dev/null
  fi

  # Mimic GNU timeout(1): rc 143 (SIGTERM) or 137 (SIGKILL) by our watcher → report 124
  if [ "$rc" -eq 143 ] || [ "$rc" -eq 137 ]; then
    rc=124
  fi
  return $rc
}

healthcheck() {
  local pct
  pct=$(df -P "$PROJECT_DIR" | awk 'NR==2 {gsub("%",""); print $5}')
  if [ "${pct:-0}" -ge 95 ]; then
    log "HEALTHCHECK FAIL: disk ${pct}% full"
    return 1
  fi

  if [ -d "$PROJECT_DIR/.git" ] && [ -f "$PROJECT_DIR/.git/index.lock" ]; then
    log "HEALTHCHECK FAIL: git index.lock present"
    return 1
  fi

  if ! command -v claude >/dev/null 2>&1; then
    log "HEALTHCHECK FAIL: claude binary not found in PATH"
    return 1
  fi

  return 0
}

cd "$PROJECT_DIR" || { log "FATAL: cannot cd to $PROJECT_DIR"; exit 1; }

log "═══ positioning-loop START — project=$PROJECT_DIR max=$MAX_CYCLES timeout=${CYCLE_TIMEOUT}s"

trap 'log "received SIGINT/SIGTERM, killing in-flight cycle and exiting"; pkill -P $$ 2>/dev/null; sleep 1; pkill -9 -P $$ 2>/dev/null; exit 0' INT TERM

while true; do
  # Convergence sentinel — cycle writes this when 8-dim scoreboard ≥9 + critique-stable
  if [ -f "$CONVERGED_SENTINEL" ]; then
    log "✓ CONVERGED.md detected — positioning loop reached convergence. Stopping."
    exit 0
  fi

  CYCLE=$(cat "$COUNTER_FILE")
  CYCLE=$((CYCLE + 1))

  if [ "$MAX_CYCLES" -gt 0 ] && [ "$CYCLE" -gt "$MAX_CYCLES" ]; then
    log "MAX_CYCLES=$MAX_CYCLES reached without convergence. Stopping."
    log "→ Next step: review docs/positioning/loop/synthesis/cycle-$(printf '%03d' $((CYCLE-1))).md and decide whether to extend."
    exit 0
  fi

  log "── cycle $CYCLE start"

  if ! healthcheck; then
    log "healthcheck failed, sleeping 5min before retry"
    sleep 300
    continue
  fi

  START_TS=$(date +%s)

  export LOOP_CYCLE="$CYCLE"
  run_with_timeout "$CYCLE_TIMEOUT" claude -p "$PROMPT" \
    --permission-mode "$PERMISSION_MODE" \
    --allowedTools "$ALLOWED_TOOLS" \
    >> "$LOG" 2>&1
  EXIT=$?
  unset LOOP_CYCLE

  END_TS=$(date +%s)
  DUR=$((END_TS - START_TS))

  echo "$CYCLE" > "$COUNTER_FILE"
  log "── cycle $CYCLE end exit=$EXIT duration=${DUR}s"

  case $EXIT in
    0)
      sleep 10
      ;;
    124)
      log "cycle timed out after ${CYCLE_TIMEOUT}s, cooling down 60s"
      sleep 60
      ;;
    130)
      log "Ctrl+C received, exiting"
      exit 0
      ;;
    137)
      log "SIGKILL received, exiting"
      exit 0
      ;;
    *)
      log "non-zero exit=$EXIT, cooling down 5min (rate limit?)"
      sleep 300
      ;;
  esac
done
